### ISSUE TITLE
Refine the sonobuoy result

### ISSUE THREAD

**Issue by yzaccc** [K8sbykeshed/k8s-service-validator#102]

**Comment by johnSchnake** [comment]
Is this related to making the output structured output, e.g. so that Sonobuoy can report on pass/fail?

During the last antrea live it came up about structured output.

Sonobuoy can support:
 - json data (the format from go-test)
 - junit
 - a manual format that you can write manually (yaml) or use our plugin-helper to do it (my recommendation) https://github.com/vmware-tanzu/sonobuoy-plugins/tree/main/plugin-helper

I'd love to take this up if thats ok
